name: ci-cd
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: 973f6f2e4a490ae8129c6a1cd17a62531c3a21c4ff8e58061802a2cf7881f88f
        with:
          coverageCommand: npm run coverage
          debug: true
name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Generate code coverage
        run: npm run coverage

      - name: Upload code coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: nKL66wNEEXyauOWoMaHkOmYFoqaaDE6v3
          path-to-lcov: ./coverage/lcov.info
      - name: Coveralls
        run: npx nyc report --reporter=text-lcov | npx coveralls
        env:
          CI: true
          COVERALLS_REPO_TOKEN: nKL66wNEEXyauOWoMaHkOmYFoqaaDE6v3

