name: CI
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: yarn

    - name: Run build
      run: yarn build

    - name: Run linter
      run: yarn lint

    - name: Run tests
      env:
        DATABASE_URL: ${{secrets.DATABASE_URL }}
        PORT: ${{secrets.PORT }}
        NODE_ENV: ${{secrets.NODE_ENV }}
        JWT_ACCESS_TOKEN_PRIVATE_KEY: ${{secrets.JWT_ACCESS_TOKEN_PRIVATE_KEY }}
        JWT_ACCESS_TOKEN_PUBLIC_KEY: ${{secrets.JWT_ACCESS_TOKEN_PUBLIC_KEY }}
        JWT_REFRESH_TOKEN_PRIVATE_KEY: ${{secrets.JWT_REFRESH_TOKEN_PRIVATE_KEY }}
        JWT_REFRESH_TOKEN_PUBLIC_KEY: ${{secrets.JWT_REFRESH_TOKEN_PUBLIC_KEY }}
      run: yarn test
